-- bigint, varchar, timestamp, date, boolean, enum
create table if not exists airflow_musteri
(
    id      bigint generated by default as identity
        constraint pk_airflow_musteri
            primary key,
    olusturma_tarihi        timestamp,
    guncelleme_tarihi       timestamp,
    p_musteri_id            bigint,
    ad                      varchar(100),
    soyad                   varchar(70),
    cinsiyet enum_musteri_cinsiyet,
    dogum_tarihi            date,
    yuksek_risk_grubunda_mi boolean,
    bank_hesap_adi          varchar(100),
    bank_hesap_no           varchar(30),
    yabanci_ad_unvan        varchar(250)
);

